frame_num: 33
motion_frames_num: 5
tgt_fps: 25
sample_rate: 16000
sample_steps: 2
sample_shift: 5
color_correction_strength: 0.0
cached_audio_duration: 8
height: 704
width: 416
audio_loudness_norm: true
t5_quant: null
t5_quant_dir: null
wan_quant: null
wan_quant_include: null
wan_quant_exclude: null
